basePath: /api
definitions:
  golang-api_internal_dto.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  golang-api_internal_dto.RegisterDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  golang-api_internal_dto.UpdateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: REST API Fiber PostgreSQL
  title: User API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/golang-api_internal_dto.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: create user baru
      parameters:
      - description: register
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/golang-api_internal_dto.RegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register user
      tags:
      - Auth
  /users:
    get:
      description: Ambil daftar user dengan pagination
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      - description: Search by name
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get users with pagination
      tags:
      - Users
  /users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update data user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/golang-api_internal_dto.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
